image: gitpod/workspace-dotnet

tasks:
  - before: chdir
    command: cd /workspace/TextTmemplateCSharp/antlr4_example && dotnet build
  - init: dotnet build
    command: cd /workspace/TextTmemplateCSharp/antlr4_example && dotnet run