image: gitpod/workspace-dotnet

tasks:
  - init: dotnet build
    command: dotnet run --project /workspace/TextTemplateCSharp/antlr4_example

vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
